[package]
name = "test1"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tui = "0.12"
termion = "1.5"
sysinfo = "0.3.19"
indexmap = "1.7.0"
fast-math = "0.1"